spring:
  application:
    name: webflux-guide
  webflux:
    base-path: /api
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/test
      database: test

  logging:
    level:
      org:
        example: DEBUG
        springFramework:
          web: INFO
          data:
            mongodb:
              core:
                ReactiveMongoTemplate: DEBUG
      reactor:
        netty:
          http:
            client: DEBUG